server:
  port: 10086  #服务端口

spring:
  application:
    name: eurekaserver    #eureka的服务名称
  cloud:
    inetutils:
      use-only-site-local-interfaces: true #只使用本地主机的ip地址(防止连接到VMware地址)
eureka:
  client:
    service-url:          #eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: false